spring:
  application:
    name: interventionservice

server:
  port: 8091

  cloud:
    config:
      enabled: true
      uri: http://localhost:8889

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
