spring:
  application:
    name: userservice
  jpa:
    database: MYSQL
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: strong


server:
  port: 8081

  cloud:
    config:
      enabled: true
      uri: http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

